In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_excel('Sales Data November 2020 - October 2023.xlsx', sheet_name='sales_2020-10_2023-10(1)')

In [3]:
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None) # Show full content

# 1.0 Data Understanding

In [4]:
df.head()

,Order ID,Sale ID,Date,Order,Transaction type,Sale type,Sales channel,Product type,Product,Net quantity,Gross sales,Discounts,Returns,Net sales,Shipping,Taxes,Total sales
0,2854884835480,8725409595544,2020-11-11T01:39:33+03:00,TS1011,product,order,Online Store,Bathing & Skin Care,Mamia Sensitive Bathing & Skin Care 64 Bathing & Skin Care,1,200.0,0.0,0,200.0,0,0.0,200.0
1,2864488448152,8752046604440,2020-11-16T16:43:01+03:00,TS1012,product,order,Point of Sale,Baby Formula,NANNYcare Growing Up Milk Goat Milk Based 3 From 1 to 3 Years 900g,2,9000.0,0.0,0,9000.0,0,0.0,9000.0
2,2864491954328,8752055845016,2020-11-16T16:45:58+03:00,TS1013,product,order,Point of Sale,Baby Diapers,DryNites Spider-Man Baby & Toddler Clothing 16pk,1,1800.0,0.0,0,1800.0,0,0.0,1800.0
3,2864491954328,8752055877784,2020-11-16T16:45:58+03:00,TS1013,product,order,Point of Sale,Bathing & Skin Care,Metanium Nappy Rash Ointment 30g,1,1500.0,0.0,0,1500.0,0,0.0,1500.0
4,2864497066136,8752070656152,2020-11-16T16:49:47+03:00,TS1014,product,order,Point of Sale,Baby Formula,Aptamil 1 First Baby Milk Formula from Birth 800g,1,3000.0,0.0,0,3000.0,0,0.0,3000.0

In [5]:
df.shape

(28755, 17)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28755 entries, 0 to 28754
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          28755 non-null  int64
 1   Sale ID           28755 non-null  int64
 2   Date              28755 non-null  object
 3   Order             28755 non-null  object
 4   Transaction type  28755 non-null  object
 5   Sale type         28755 non-null  object
 6   Sales channel     28755 non-null  object
 7   Product type      17244 non-null  object
 8   Product           27845 non-null  object
 9   Net quantity      28755 non-null  int64
 10  Gross sales       28755 non-null  float64
 11  Discounts         28755 non-null  float64
 12  Returns           28755 non-null  int64
 13  Net sales         28755 non-null  float64
 14  Shipping          28755 non-null  int64
 15  Taxes             28755 non-null  float64
 16  Total sales       28755 non-null  float64
dtypes: float64(5), int64(5), object(7)
memory usage: 3.7+ MB

In [7]:
df.describe(include='all')

,Order ID,Sale ID,Date,Order,Transaction type,Sale type,Sales channel,Product type,Product,Net quantity,Gross sales,Discounts,Returns,Net sales,Shipping,Taxes,Total sales
count,2.875500e+04,2.875500e+04,28755,28755,28755,28755,28755,17244,27845,28755.000000,28755.000000,28755.000000,28755.000000,28755.000000,28755.000000,28755.000000,28755.000000
unique,NaN,NaN,13434,13257,4,2,3,100,1923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,2022-04-20T14:40:59+03:00,TS5441,product,order,Point of Sale,Baby Formula,Rider,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,24,24,27843,28438,25696,5727,1062,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,4.725462e+12,1.502482e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.348392,2901.054775,-8.046427,-23.983551,2869.024798,9.871327,0.330354,2879.226479
std,6.424951e+11,2.100030e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.327027,4470.603559,179.058569,487.065277,4486.248651,71.716823,15.286252,4480.645026
min,2.854885e+12,8.725410e+12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-12.000000,0.000000,-16200.000000,-38400.000000,-38400.000000,-800.000000,-112.000000,-38400.000000
25%,4.601180e+12,1.472930e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,420.000000,0.000000,0.000000,420.000000,0.000000,0.000000,450.000000
50%,4.953558e+12,1.584411e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1500.000000,0.000000,0.000000,1500.000000,0.000000,0.000000,1500.000000
75%,5.182479e+12,1.648706e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,3300.000000,0.000000,0.000000,3300.000000,0.000000,0.000000,3300.000000
max,5.390480e+12,1.708426e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.000000,102000.000000,0.000000,8500.000000,102000.000000,800.000000,1600.000000,102000.000000

# 2.0 Data Cleaning

### 2.1 Duplicate Data Analysis

In [8]:
# Checking for duplicate records
df.duplicated().sum()

np.int64(0)

### 2.2 Missing Value Analysis

In [9]:
# Checking missing values
df.isnull().sum()

Order ID                0
Sale ID                 0
Date                    0
Order                   0
Transaction type        0
Sale type               0
Sales channel           0
Product type        11511
Product               910
Net quantity            0
Gross sales             0
Discounts               0
Returns                 0
Net sales               0
Shipping                0
Taxes                   0
Total sales             0
dtype: int64

`Product type` and `Product` has a very large number of missing values which may impact product-level analysis. Further investigation is required to determine whether these should be removed.

In [10]:
df[df.isnull().any(axis=1)].head()

,Order ID,Sale ID,Date,Order,Transaction type,Sale type,Sales channel,Product type,Product,Net quantity,Gross sales,Discounts,Returns,Net sales,Shipping,Taxes,Total sales
7,2864504438936,8752091234456,2020-11-16T16:56:04+03:00,TS1015,product,order,Point of Sale,NaN,Rider,1,300.0,0.0,0,300.0,0,0.0,300.0
19,2864990027928,8753513791640,2020-11-16T22:05:20+03:00,TS1020,shipping,order,Online Store,NaN,NaN,0,0.0,0.0,0,0.0,300,0.0,300.0
25,2865926504600,8756131233944,2020-11-17T12:26:52+03:00,TS1023,product,order,Point of Sale,NaN,Rider,1,150.0,0.0,0,150.0,0,24.0,174.0
35,2866079400088,8756561903768,2020-11-17T15:01:44+03:00,TS1026,product,order,Point of Sale,NaN,Rider,1,200.0,0.0,0,200.0,0,32.0,232.0
42,2866268700824,8757130330264,2020-11-17T17:36:38+03:00,TS1029,product,order,Point of Sale,NaN,Rider,1,240.0,0.0,0,240.0,0,0.0,240.0

In [11]:
product_type_null = df['Product type'].isnull().sum()
product_null = df['Product'].isnull().sum()
both_null = (df['Product type'].isnull() & df['Product'].isnull()).sum()

print(f"Product type missing: {product_type_null} ({product_type_null/len(df)*100:.2f}%)")
print(f"Product missing: {product_null} ({product_null/len(df)*100:.2f}%)")
print(f"Both missing: {both_null} ({both_null/len(df)*100:.2f}%)")

Product type missing: 11511 (40.03%)
Product missing: 910 (3.16%)
Both missing: 910 (3.16%)

In [12]:
df[df['Product type'].isnull()]['Product'].value_counts().head(20)

Product
Rider                                                1062
Rider Rajab                                           849
Rider Peter                                           791
Rajab                                                 527
Peter                                                 433
Rider Swahili                                         423
Rider Jeff                                            217
Aptamil 2 Follow On Milk Powder 800G                  195
Fargo                                                 195
Aptamil 1 First Baby Milk Formula from Birth 800g     181
Bus                                                   161
Rider Francis                                         156
Rider George                                          149
Rider rajab                                           146
Aptamil Creamed Banana - Feeding and weaning 125g     143
Aptamil Creamed Porridge  4 Month Plus, 125g          136
Delivery                                              130
Aptamil 3 Growing Up Milk Formula 800g                117
George                                                112
Rider (Jeff)                                          112
Name: count, dtype: int64

When `Product type` is null, the `Product` field is mostly dominated by **logistics-related entries**. Since this analysis focuses on product sales performance and customer purchasing behavior, all null rows will be removed.

In [13]:
df = df.dropna()

df.reset_index(drop=True, inplace=True)

print(df.shape)

(17244, 17)

### 2.3 Handling Inconsistent Data Entries

In [14]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns

# For each categorical column, identify duplicated categories
for col in categorical_cols:
    print(f"\nColumn: {col}")
    # Create a lowercase version to group similar categories
    lower_case_counts = df[col].astype(str).str.strip().str.lower().value_counts()
    
    # Find groups with more than one distinct capitalization
    duplicates = {}
    for category_lower in lower_case_counts.index:
        original_variants = df[df[col].str.strip().str.lower() == category_lower][col].unique()
        if len(original_variants) > 1:
            duplicates[category_lower] = original_variants
    
    if duplicates:
        print("Categories with capitalization differences:")
        for lower_cat, variants in duplicates.items():
            print(f"  '{lower_cat}': {variants}")
    else:
        print("No capitalization duplicates found.")

Column: Date
No capitalization duplicates found.

Column: Order
No capitalization duplicates found.

Column: Transaction type
No capitalization duplicates found.

Column: Sale type
No capitalization duplicates found.

Column: Sales channel
No capitalization duplicates found.

Column: Product type
Categories with capitalization differences:
  'baby formula': ['Baby Formula' 'baby Formula' ' Baby Formula' 'baby formula']
  'baby diapers': ['Baby Diapers' ' Baby Diapers']
  'sterilising fluid': ['Sterilising Fluid' 'Sterilising fluid']
  'baby teething soothers': ['Baby Teething Soothers' 'baby Teething Soothers']
  'nipple cream': ['nipple cream' 'Nipple Cream']
  'car seat': ['Car Seat' 'Car seat']
  'baby gift sets': ['Baby Gift Sets' 'Baby gift sets']
  'baby stroller': ['Baby stroller' 'Baby Stroller']

Column: Product
Categories with capitalization differences:
  'smiggle lets play junior drink bottle, 440ml': ['Smiggle Lets Play Junior Drink Bottle, 440Ml'
 'Smiggle Lets Play Junior Drink Bottle, 440ML']
  'tommee tippee orthodontic anytime teething soothers 2pk': ['Tommee Tippee Orthodontic Anytime Teething Soothers 2pk'
 'Tommee Tippee Orthodontic anytime Teething Soothers 2pk']

In [15]:
# Apply title case cleaning to all such columns
for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip().str.title()

In [16]:
for col in categorical_cols:
    print(f"{col}:")
    print(df[col].unique(), "\n")

Date:
['2020-11-11T01:39:33+03:00' '2020-11-16T16:43:01+03:00'
 '2020-11-16T16:45:58+03:00' ... '2023-10-31T17:36:00+03:00'
 '2023-10-31T18:24:58+03:00' '2023-10-31T18:26:21+03:00']

Order:
['Ts1011' 'Ts1012' 'Ts1013' ... 'Ts14273' 'Ts14274' 'Ts14275']

Transaction type:
['Product' 'Gift_Card']

Sale type:
['Order' 'Return']

Sales channel:
['Online Store' 'Point Of Sale' 'Draft Orders']

Product type:
['Bathing & Skin Care' 'Baby Formula' 'Baby Diapers' 'Feeding And Weaning'
 'Toys & Games & Gifts' 'Sterilising Tablets' 'Bottles & Bottling Sets'
 'Breast Pump' 'Safety & Wellness' 'Baby Baby & Toddler Clothing'
 'Nappy Bags' 'Feeding And Weanings' 'Baby Toothbrush' 'Sterilising Fluid'
 'Nipple Cream' 'Baby Bedding' 'Potty Training' 'Bowls'
 'Teething Soothers' 'Laundry Equipment' 'Maternity & Nursing'
 'Baby & Toddler Clothing' 'Baby Nappies' 'Bibs' 'Fabric Conditioner'
 'Sanitising Water' 'Nursery' 'Car Seat' 'Height Measurement Sticker'
 'Milk Storage Bags' 'Tooth Brush' 'Kids Toothpaste' 'Straw Cup'
 'Pull Ups' 'Diaper Pants' 'Swim Nappies' 'Baby Sleeping Bag'
 'Baby Carrier & Accessories' 'Kids Multivitamins' 'Baby Potties'
 'Play Tent' 'Electric Steriliser' 'Bed Mats' 'Electric Toothbrush'
 'Chocolates' 'Popper Fidget' 'Diaper Disposal Refills' 'Dining Set'
 'Kids Mask' 'Hair Styling Products' 'Walkers' 'No -Touch Thermometer'
 'Gift Set' 'Kids Scooters' 'Lunch Boxes & Totes' 'Baby Teething Soothers'
 'Pen & Pencil Cases' 'Backpacks' 'Toys & Games & Gifts & Games'
 'Kids Sports Bottle' 'Hand Sanitiser' 'Nasal Aspirators' 'Odour Spray'
 'Story & Novelty Books' 'Vapopads Refills' 'Kids Tablet'
 'Candy & Chocolate' 'Colouring Book' 'Sleeping Aids' 'Nipple Shield'
 'Baby Gift Sets' 'Baby Health & Grooming Kits'
 'High Chairs & Booster Seats' 'Laundry Detergent' 'Changing Bag' 'Socks'
 'Formula Storage Box' 'Suitcases' 'Bathtubs' 'Baby Monitor'
 'Baby Health & Grooming Kits & Grooming Kits'
 'Baby Safety Locks & Guards' 'Washcloth' 'Laundry Bag'
 'Tommee Tippee Breast Pads' 'Milk Powder Dispenser'
 'Baby Walkers & Entertainers' 'Reusable Nappies'
 'Baby Activity Toys & Games & Gifts' 'Baby Stroller']

Product:
['Mamia Sensitive Bathing & Skin Care 64 Bathing & Skin Care'
 'Nannycare Growing Up Milk Goat Milk Based 3 From 1 To 3 Years 900G'
 'Drynites Spider-Man Baby & Toddler Clothing 16Pk' ...
 'Summer Infant Deluxe Comfort Folding Booster Seat Teal, 6+ Months'
 'Mamas & Papas Chenille Blanket - Grey Star'
 'Childs Farm Bubble Bath Organic Raspberry, 250Ml']

# 3.0 Feature Engineering

### 3.1 Extracting Time-Based Features

In [17]:
df['Date'] = pd.to_datetime(df['Date'], utc=False) 

df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.month_name()
df['Month_Year'] = pd.to_datetime(df[['Year', 'Month']].assign(DAY=1))
df['Day'] = df['Date'].dt.day
df['Week'] = df['Date'].dt.isocalendar().week
df['Weekday'] = df['Date'].dt.day_name()
df['Hour'] = df['Date'].dt.hour

date_related_cols = ['Date', 'Year', 'Month', 'Month_Name', 'Month_Year','Day', 'Week', 'Weekday', 'Hour']

other_cols = [col for col in df.columns if col not in date_related_cols]
df = df[date_related_cols + other_cols]
df

,Date,Year,Month,Month_Name,Month_Year,Day,Week,Weekday,Hour,Order ID,Sale ID,Order,Transaction type,Sale type,Sales channel,Product type,Product,Net quantity,Gross sales,Discounts,Returns,Net sales,Shipping,Taxes,Total sales
0,2020-11-11 01:39:33+03:00,2020,11,November,2020-11-01,11,46,Wednesday,1,2854884835480,8725409595544,Ts1011,Product,Order,Online Store,Bathing & Skin Care,Mamia Sensitive Bathing & Skin Care 64 Bathing & Skin Care,1,200.0,0.0,0,200.0,0,0.0,200.0
1,2020-11-16 16:43:01+03:00,2020,11,November,2020-11-01,16,47,Monday,16,2864488448152,8752046604440,Ts1012,Product,Order,Point Of Sale,Baby Formula,Nannycare Growing Up Milk Goat Milk Based 3 From 1 To 3 Years 900G,2,9000.0,0.0,0,9000.0,0,0.0,9000.0
2,2020-11-16 16:45:58+03:00,2020,11,November,2020-11-01,16,47,Monday,16,2864491954328,8752055845016,Ts1013,Product,Order,Point Of Sale,Baby Diapers,Drynites Spider-Man Baby & Toddler Clothing 16Pk,1,1800.0,0.0,0,1800.0,0,0.0,1800.0
3,2020-11-16 16:45:58+03:00,2020,11,November,2020-11-01,16,47,Monday,16,2864491954328,8752055877784,Ts1013,Product,Order,Point Of Sale,Bathing & Skin Care,Metanium Nappy Rash Ointment 30G,1,1500.0,0.0,0,1500.0,0,0.0,1500.0
4,2020-11-16 16:49:47+03:00,2020,11,November,2020-11-01,16,47,Monday,16,2864497066136,8752070656152,Ts1014,Product,Order,Point Of Sale,Baby Formula,Aptamil 1 First Baby Milk Formula From Birth 800G,1,3000.0,0.0,0,3000.0,0,0.0,3000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17239,2023-10-31 16:05:55+03:00,2023,10,October,2023-10-01,31,44,Tuesday,16,5390355464447,17083875262719,Ts14271,Product,Order,Point Of Sale,Baby Formula,Aptamil (Uk) Stage 1 First Infant Milk Powder From Birth 800G,2,7600.0,0.0,0,7600.0,0,0.0,7600.0
17240,2023-10-31 17:02:30+03:00,2023,10,October,2023-10-01,31,44,Tuesday,17,5390404387071,17084025635071,Ts14272,Product,Order,Point Of Sale,Toys & Games & Gifts,"Mega Bloks Build & Learn Table, 1-5Years, Blue/ Pink",1,6999.0,0.0,0,6999.0,0,0.0,6999.0
17241,2023-10-31 17:36:00+03:00,2023,10,October,2023-10-01,31,44,Tuesday,17,5390433911039,17084115615999,Ts14273,Product,Order,Point Of Sale,Baby Formula,"Nannycare 2 Follow On Milk Goat Milk Based From 6+Months, 900G",1,6000.0,0.0,0,6000.0,0,0.0,6000.0
17242,2023-10-31 18:24:58+03:00,2023,10,October,2023-10-01,31,44,Tuesday,18,5390478442751,17084252094719,Ts14274,Product,Order,Point Of Sale,Baby Formula,Aptamil (Uk) Stage 3 Toddler Milk Powder 800G,2,7600.0,0.0,0,7600.0,0,0.0,7600.0
17243,2023-10-31 18:26:21+03:00,2023,10,October,2023-10-01,31,44,Tuesday,18,5390479655167,17084255699199,Ts14275,Product,Order,Point Of Sale,Bathing & Skin Care,"Rascal & Friends Premium Nappy Pants Size 7, 22 Pack",3,7800.0,0.0,0,7800.0,0,0.0,7800.0

### Time-based filtering

Data for 2023 is only available up to October. Q4 2023 is excluded to ensure consistency in time-based analysis.

In [18]:
df = df[~((df['Date'].dt.year == 2023) & (df['Date'].dt.quarter == 4))]

### 3.2 Discount Rate Calculation

In [19]:
# Compute Discount Rate only for rows with non-zero Discounts
df['Discount Rate'] = 0.0 
non_zero_mask = df['Discounts'] != 0

df.loc[non_zero_mask, 'Discount Rate'] = (
    (df.loc[non_zero_mask, 'Discounts'].abs() / df.loc[non_zero_mask, 'Gross sales'])
    .replace([np.inf, -np.inf], np.nan)
    .round(2)
)

# Move 'Discount Rate' column after 'Discounts'
cols = df.columns.tolist()
cols.remove('Discount Rate')
insert_index = cols.index('Discounts') + 1
cols.insert(insert_index, 'Discount Rate')

df = df[cols]

df[(df['Discounts'] != 0)].head(5)

,Date,Year,Month,Month_Name,Month_Year,Day,Week,Weekday,Hour,Order ID,Sale ID,Order,Transaction type,Sale type,Sales channel,Product type,Product,Net quantity,Gross sales,Discounts,Discount Rate,Returns,Net sales,Shipping,Taxes,Total sales
84,2020-11-19 17:42:51+03:00,2020,11,November,2020-11-01,19,47,Thursday,17,2870374924440,8768673841304,Ts1050,Product,Order,Point Of Sale,Baby Baby & Toddler Clothing,Catimini Parrot Print Percale Dress,1,3500.0,-767.65,0.22,0,2732.35,0,0.0,2732.35
85,2020-11-19 17:42:51+03:00,2020,11,November,2020-11-01,19,47,Thursday,17,2870374924440,8768673874072,Ts1050,Product,Order,Point Of Sale,Baby Baby & Toddler Clothing,Catimini Dress In Two Materials - Fuchsia,1,3500.0,-767.65,0.22,0,2732.35,0,0.0,2732.35
86,2020-11-19 17:42:51+03:00,2020,11,November,2020-11-01,19,47,Thursday,17,2870374924440,8768673743000,Ts1050,Product,Order,Point Of Sale,Safety & Wellness,Lindam Sure Shut Axis Safety & Wellness 76 - 82 Cm - Pressure Fit,2,24000.0,-5263.89,0.22,0,18736.11,0,0.0,18736.11
87,2020-11-19 17:42:51+03:00,2020,11,November,2020-11-01,19,47,Thursday,17,2870374924440,8768673808536,Ts1050,Product,Order,Point Of Sale,Bathing & Skin Care,"Huggies Pull Ups Potty Training Pants Girls 1-2.5 Years, 17 Pants",1,2000.0,-438.66,0.22,0,1561.34,0,0.0,1561.34
88,2020-11-19 17:42:51+03:00,2020,11,November,2020-11-01,19,47,Thursday,17,2870374924440,8768673775768,Ts1050,Product,Order,Point Of Sale,Safety & Wellness,Lindam Safety & Wellness 28 Cm Universal Extension - White,2,9000.0,-1973.96,0.22,0,7026.04,0,0.0,7026.04

### 3.3 Product Category Mapping

In [20]:
unique_product_types = df['Product type'].unique()
print(unique_product_types)

['Bathing & Skin Care' 'Baby Formula' 'Baby Diapers' 'Feeding And Weaning'
 'Toys & Games & Gifts' 'Sterilising Tablets' 'Bottles & Bottling Sets'
 'Breast Pump' 'Safety & Wellness' 'Baby Baby & Toddler Clothing'
 'Nappy Bags' 'Feeding And Weanings' 'Baby Toothbrush' 'Sterilising Fluid'
 'Nipple Cream' 'Baby Bedding' 'Potty Training' 'Bowls'
 'Teething Soothers' 'Laundry Equipment' 'Maternity & Nursing'
 'Baby & Toddler Clothing' 'Baby Nappies' 'Bibs' 'Fabric Conditioner'
 'Sanitising Water' 'Nursery' 'Car Seat' 'Height Measurement Sticker'
 'Milk Storage Bags' 'Tooth Brush' 'Kids Toothpaste' 'Straw Cup'
 'Pull Ups' 'Diaper Pants' 'Swim Nappies' 'Baby Sleeping Bag'
 'Baby Carrier & Accessories' 'Kids Multivitamins' 'Baby Potties'
 'Play Tent' 'Electric Steriliser' 'Bed Mats' 'Electric Toothbrush'
 'Chocolates' 'Popper Fidget' 'Diaper Disposal Refills' 'Dining Set'
 'Kids Mask' 'Hair Styling Products' 'Walkers' 'No -Touch Thermometer'
 'Gift Set' 'Kids Scooters' 'Lunch Boxes & Totes' 'Baby Teething Soothers'
 'Pen & Pencil Cases' 'Backpacks' 'Toys & Games & Gifts & Games'
 'Kids Sports Bottle' 'Hand Sanitiser' 'Nasal Aspirators' 'Odour Spray'
 'Story & Novelty Books' 'Vapopads Refills' 'Kids Tablet'
 'Candy & Chocolate' 'Colouring Book' 'Sleeping Aids' 'Nipple Shield'
 'Baby Gift Sets' 'Baby Health & Grooming Kits'
 'High Chairs & Booster Seats' 'Laundry Detergent' 'Changing Bag' 'Socks'
 'Formula Storage Box' 'Suitcases' 'Bathtubs' 'Baby Monitor'
 'Baby Health & Grooming Kits & Grooming Kits'
 'Baby Safety Locks & Guards' 'Washcloth' 'Laundry Bag'
 'Tommee Tippee Breast Pads' 'Milk Powder Dispenser'
 'Baby Walkers & Entertainers' 'Reusable Nappies'
 'Baby Activity Toys & Games & Gifts' 'Baby Stroller']

The `Product type` column contains a large number ofinconsistent categories, making analysis difficult. To improve interpretability, we group similar product types into higher-level categories.

In [21]:
product_category_mapping = {
    # Baby Care & Hygiene
    'Bathing & Skin Care': 'Baby Care & Hygiene',
    'Baby Toothbrush': 'Baby Care & Hygiene',
    'Tooth Brush': 'Baby Care & Hygiene',
    'Kids Toothpaste': 'Baby Care & Hygiene',
    'Nasal Aspirators': 'Baby Care & Hygiene',
    'Sterilising Tablets': 'Baby Care & Hygiene',
    'Sterilising Fluid': 'Baby Care & Hygiene',
    'Hand Sanitiser': 'Baby Care & Hygiene',
    'Sanitising Water': 'Baby Care & Hygiene',
    'Odour Spray': 'Baby Care & Hygiene',
    'Washcloth': 'Baby Care & Hygiene',
    'Bathtubs': 'Baby Care & Hygiene',
    'No -Touch Thermometer': 'Baby Care & Hygiene',
    'Electric Steriliser': 'Baby Care & Hygiene',
    'Electric Toothbrush': 'Baby Care & Hygiene',

    # Grooming
    'Hair Styling Products': 'Grooming',
    'Baby Health & Grooming Kits': 'Grooming',
    'Baby Health & Grooming Kits & Grooming Kits': 'Grooming',

    # Laundry
    'Fabric Conditioner': 'Laundry',
    'Laundry Equipment': 'Laundry',
    'Laundry Detergent': 'Laundry',
    'Laundry Bag': 'Laundry',

    # Feeding & Nursing
    'Baby Formula': 'Feeding & Nursing',
    'Feeding And Weaning': 'Feeding & Nursing',
    'Feeding And Weanings': 'Feeding & Nursing',
    'Bottles & Bottling Sets': 'Feeding & Nursing',
    'Kids Sports Bottle': 'Feeding & Nursing',
    'Breast Pump': 'Feeding & Nursing',
    'Nipple Shield': 'Feeding & Nursing',
    'Nipple Cream': 'Feeding & Nursing',
    'Milk Storage Bags': 'Feeding & Nursing',
    'Milk Powder Dispenser': 'Feeding & Nursing',
    'Formula Storage Box': 'Feeding & Nursing',
    'Straw Cup': 'Feeding & Nursing',
    'Bowls': 'Feeding & Nursing',
    'Dining Set': 'Feeding & Nursing',
    'Teething Soothers': 'Feeding & Nursing',
    'Baby Teething Soothers': 'Feeding & Nursing',

    # Diapers & Potty
    'Baby Diapers': 'Diapers & Potty',
    'Baby Nappies': 'Diapers & Potty',
    'Pull Ups': 'Diapers & Potty',
    'Diaper Pants': 'Diapers & Potty',
    'Swim Nappies': 'Diapers & Potty',
    'Diaper Disposal Refills': 'Diapers & Potty',
    'Reusable Nappies': 'Diapers & Potty',
    'Potty Training': 'Diapers & Potty',
    'Baby Potties': 'Diapers & Potty',

    # Clothing & Accessories
    'Baby Baby & Toddler Clothing': 'Clothing & Accessories',
    'Baby & Toddler Clothing': 'Clothing & Accessories',
    'Socks': 'Clothing & Accessories',
    'Nappy Bags': 'Clothing & Accessories',
    'Changing Bag': 'Clothing & Accessories',
    'Bibs': 'Clothing & Accessories',

    # Toys, Games & Gifts
    'Toys & Games & Gifts': 'Toys, Games & Gifts',
    'Toys & Games & Gifts & Games': 'Toys, Games & Gifts',
    'Baby Activity Toys & Games & Gifts': 'Toys, Games & Gifts',
    'Play Tent': 'Toys, Games & Gifts',
    'Popper Fidget': 'Toys, Games & Gifts',
    'Story & Novelty Books': 'Toys, Games & Gifts',
    'Colouring Book': 'Toys, Games & Gifts',
    'Kids Tablet': 'Toys, Games & Gifts',
    'Kids Mask': 'Toys, Games & Gifts',
    'Kids Scooters': 'Toys, Games & Gifts',
    'Pen & Pencil Cases': 'Toys, Games & Gifts',
    'Gift Set': 'Toys, Games & Gifts',
    'Baby Gift Sets': 'Toys, Games & Gifts',

    # Nursery & Bedding
    'Baby Bedding': 'Nursery & Bedding',
    'Baby Sleeping Bag': 'Nursery & Bedding',
    'Nursery': 'Nursery & Bedding',
    'Bed Mats': 'Nursery & Bedding',
    'Sleeping Aids': 'Nursery & Bedding',
    'Height Measurement Sticker': 'Nursery & Bedding',
    'Baby Monitor': 'Nursery & Bedding',

    # Travel
    'Baby Carrier & Accessories': 'Travel',
    'Walkers': 'Travel',
    'Baby Walkers & Entertainers': 'Travel',
    'Baby Stroller': 'Travel',
    'Car Seat': 'Travel',
    'Suitcases': 'Travel',
    'Baby Safety Locks & Guards': 'Travel',
    'Lunch Boxes & Totes': 'Travel',
    'High Chairs & Booster Seats': 'Travel',
    'Backpacks': 'Travel',

    # Maternity & Nursing
    'Maternity & Nursing': 'Maternity & Nursing',
    'Tommee Tippee Breast Pads': 'Maternity & Nursing',

    # Sweets
    'Chocolates': 'Sweets',
    'Candy & Chocolate': 'Sweets',

    # Shipping
    'Shipping': 'Shipping',

    # Health & Wellness
    'Vapopads Refills': 'Health & Wellness',
    'Kids Multivitamins': 'Health & Wellness',
    'Safety & Wellness': 'Health & Wellness',
}

In [22]:
df['Product Category'] = df['Product type'].map(product_category_mapping).fillna('Other')

In [23]:
product_mapping_df = df[['Product type']].drop_duplicates().copy()
product_mapping_df['Product Category'] = product_mapping_df['Product type'].map(product_category_mapping).fillna('Other')
product_mapping_df = product_mapping_df.sort_values(by='Product Category')

product_mapping_df

                      Product type     Product Category
0              Bathing & Skin Care  Baby Care & Hygiene
383               Sanitising Water  Baby Care & Hygiene
7985                      Bathtubs  Baby Care & Hygiene
2882         No -Touch Thermometer  Baby Care & Hygiene
8954                     Washcloth  Baby Care & Hygiene
...                            ...                  ...
3050           Lunch Boxes & Totes               Travel
6772   High Chairs & Booster Seats               Travel
3069                     Backpacks               Travel
8743    Baby Safety Locks & Guards               Travel
15504                Baby Stroller               Travel

[90 rows x 2 columns]

In [24]:
unique_product_categories = df['Product Category'].unique()
print(unique_product_categories)

['Baby Care & Hygiene' 'Feeding & Nursing' 'Diapers & Potty'
 'Toys, Games & Gifts' 'Health & Wellness' 'Clothing & Accessories'
 'Nursery & Bedding' 'Laundry' 'Maternity & Nursing' 'Travel' 'Sweets'
 'Grooming']

In [25]:
category_counts = df.groupby('Product Category')['Product type'].nunique().sort_values(ascending=False)
print(category_counts)

Product Category
Feeding & Nursing         16
Baby Care & Hygiene       15
Toys, Games & Gifts       13
Travel                    10
Diapers & Potty            9
Nursery & Bedding          7
Clothing & Accessories     6
Laundry                    4
Grooming                   3
Health & Wellness          3
Maternity & Nursing        2
Sweets                     2
Name: Product type, dtype: int64

In [26]:
df.to_csv("ecommerce_sales_data_cleaned.csv", index=False)